-- first, remove the table if it exists
drop table if exists bookmarks


-- create the table anew
create table customers (
    id INTEGER primary key generated by default as identity,
    name text, 
    id TEXT PRIMARY KEY, 
    title TEXT NOT NULL, url TEXT NOT NULL, 
    rating INTEGER, 
    description TEXT
);
  

--insert some test data
-- using a multi-row insert statement here
insert into bookmarks (id, title, url, description, rating) values
    ('ba3f9923-09b0-4e96-b276-da33dbf588a5', 'Google', 'http://google.com','An indie search engine startup', 4),
    ('ded3afa7-8062-4bcf-8634-9a4119beba7a', 'Facebook', 'http://facebook.com','everyone you went to highschool with', 1),
    ('e4f0c446-e071-4e86-b39f-587d05d35b2a', 'LinkedIn', 'http://linkedin.com','brag about your accomplishments', 2),  
    ('0798fa12-b7e5-43aa-850e-ec2d255a30fd', 'Thinkful', 'http://thinkful.com','great place to learn', 5), 
    ('bc90ae2c-ad44-4c67-835a-74db62564d1e', 'Instagram', 'http://instagram.com','highlight reel', 3),  
    ('4b3d7c13-277e-421e-beb6-4229137b593c', 'Wikipedia', 'http://wikipedia.org','information at your fingertips', 4),  
    ('30b3f8d9-d18a-4e72-ae76-d0097f7bf68b', 'Madewell', 'http://madewell.com','good place to shop', 3),  
    ('7997d002-ddb1-4464-9ae8-c52b569c4a64', 'Airbnb', 'http://airbnb.com','book your dream vacation', 5),  
    ('4a7b7d15-6739-42ff-acd1-ba010bd65d6e', 'Southwest', 'http://southwest.com','cheap flights, if you book early', 4),  
    ('94f6f2a1-48e4-4d3a-9918-3805482db8d0', 'Expedia', 'http://expedia.com','compare flights', 4);
